# Generated by Django 2.0.13 on 2019-11-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20191106_1959'),
        ('user', '0001_initial'),
        ('userballot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBallotRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Ballot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
