# Generated by Django 2.0.13 on 2019-11-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='end_time',
            field=models.IntegerField(verbose_name='종료 시간'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='start_time',
            field=models.IntegerField(verbose_name='시작 시간'),
        ),
    ]
