# Generated by Django 2.0.13 on 2019-11-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_userballot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userballot',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserBallot',
        ),
    ]
