# Generated by Django 2.0.13 on 2019-11-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_ballot_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('code', models.TextField(verbose_name='검증코드')),
                ('start_time', models.IntegerField(verbose_name='시작 시간')),
                ('end_time', models.IntegerField(verbose_name='종료 시간')),
            ],
        ),
    ]
