# Generated by Django 2.0.13 on 2019-12-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='voter_list',
            field=models.TextField(default='[]', verbose_name='투표자 리스트'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='candidate_list',
            field=models.TextField(verbose_name='후보자 리스트'),
        ),
    ]
