# Generated by Django 2.0.13 on 2019-10-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('eth_pub_key', models.CharField(max_length=42)),
                ('eth_prv_key', models.CharField(max_length=42)),
            ],
        ),
    ]
